services:
  fastapi:
    build:
      target: dev
    volumes:
      - ../backend/fastapi/app:/project/app

  inference_worker:
    build:
      target: dev
    volumes:
      - ../backend/inference_worker/app:/project/app
    depends_on:
      redis:
        condition: service_started
      triton:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        reservations:
          devices:
          -  driver: nvidia
             count: all
             capabilities: [gpu]

  frontend:
    build:
      target: dev
    volumes:
      - ../frontend/app:/app
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s